// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'changes': string;
  'changesTable': string;
  'editor': string;
  'emptyChanges': string;
  'heading': string;
  'templateControls': string;
}
export const cssExports: CssExports;
export default cssExports;
