// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'candidate': string;
  'candidateAuthor': string;
  'candidateContent': string;
  'candidateMeta': string;
  'candidateSubline': string;
  'candidateTitle': string;
  'checkInput': string;
  'confidence': string;
  'confidenceFill': string;
  'confidenceTrack': string;
  'confidenceValue': string;
  'dateAdded': string;
  'inlineAction': string;
  'noConfidence': string;
  'path': string;
  'progressStatus': string;
  'quality': string;
  'reason': string;
  'reasonDetail': string;
  'reasonLabel': string;
  'reasonList': string;
  'reviewMeta': string;
  'reviewModal': string;
  'reviewSection': string;
  'reviewSectionTitle': string;
  'reviewSummary': string;
  'reviewTitle': string;
  'size': string;
  'status': string;
  'step': string;
  'stepDetail': string;
  'stepLabel': string;
  'stepList': string;
  'suggestionMeta': string;
  'transcript': string;
}
export const cssExports: CssExports;
export default cssExports;
