// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteButton': string;
  'hideMetadataProfile': string;
  'labelIcon': string;
  'message': string;
  'preview': string;
  'previewBucket': string;
  'previewBuckets': string;
  'previewLoading': string;
  'previewSample': string;
  'previewSampleReason': string;
  'previewSampleTitle': string;
  'previewSamples': string;
  'previewSummary': string;
}
export const cssExports: CssExports;
export default cssExports;
