// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aliasEditor': string;
  'aliasList': string;
  'aliasPanel': string;
  'detailPanel': string;
  'detailTitle': string;
  'emptyMessage': string;
  'exampleMeta': string;
  'examples': string;
  'filterButtons': string;
  'identityNote': string;
  'narratorHeader': string;
  'narratorList': string;
  'narratorMeta': string;
  'narratorName': string;
  'narratorRow': string;
  'narratorStat': string;
  'narratorStats': string;
  'rowActions': string;
  'sourceCount': string;
  'sourceCounts': string;
  'workList': string;
  'workMeta': string;
  'workPath': string;
  'workRow': string;
  'workTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
