// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailPanel': string;
  'detailTitle': string;
  'emptyMessage': string;
  'exampleMeta': string;
  'examples': string;
  'filterButtons': string;
  'narratorHeader': string;
  'narratorList': string;
  'narratorMeta': string;
  'narratorName': string;
  'narratorRow': string;
  'rowActions': string;
  'sourceCount': string;
  'sourceCounts': string;
  'workList': string;
  'workMeta': string;
  'workPath': string;
  'workRow': string;
  'workTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
