// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyMessage': string;
  'exampleMeta': string;
  'examples': string;
  'filterButtons': string;
  'narratorHeader': string;
  'narratorList': string;
  'narratorMeta': string;
  'narratorName': string;
  'narratorRow': string;
  'sourceCount': string;
  'sourceCounts': string;
}
export const cssExports: CssExports;
export default cssExports;
