// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsCell': string;
  'availableText': string;
  'emptyMessage': string;
  'muted': string;
  'overviewItem': string;
  'overviewList': string;
  'overviewMain': string;
  'overviewStats': string;
  'overviewStatus': string;
  'posterArt': string;
  'posterBody': string;
  'posterFooter': string;
  'posterGrid': string;
  'posterItem': string;
  'posterTitle': string;
  'progressFill': string;
  'progressText': string;
  'progressTrack': string;
  'progressWrap': string;
  'seriesMeta': string;
  'seriesTitle': string;
  'titleCell': string;
  'warningText': string;
}
export const cssExports: CssExports;
export default cssExports;
