// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionButtonIcon': string;
  'author': string;
  'bookCount': string;
  'bookType': string;
  'bookTypeLabel': string;
  'books': string;
  'completeness': string;
  'footer': string;
  'header': string;
  'left': string;
  'monitored': string;
  'position': string;
  'reason': string;
  'seriesTitle': string;
  'status': string;
  'summary': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
