// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsCell': string;
  'actionsHeaderCell': string;
  'authorCountHeaderCell': string;
  'authorsCell': string;
  'authorsHeaderCell': string;
  'availableBooksHeaderCell': string;
  'availableText': string;
  'cell': string;
  'emptyMessage': string;
  'headerCell': string;
  'missingBooksHeaderCell': string;
  'monitoredCell': string;
  'monitoredHeaderCell': string;
  'muted': string;
  'numericCell': string;
  'overviewAuthors': string;
  'overviewItem': string;
  'overviewLabel': string;
  'overviewList': string;
  'overviewMain': string;
  'overviewStats': string;
  'overviewStatus': string;
  'posterArt': string;
  'posterBody': string;
  'posterFooter': string;
  'posterGrid': string;
  'posterItem': string;
  'posterTitle': string;
  'progressFill': string;
  'progressText': string;
  'progressTrack': string;
  'progressWrap': string;
  'seriesMeta': string;
  'seriesTitle': string;
  'tableContainer': string;
  'titleCell': string;
  'titleHeaderCell': string;
  'totalBooksHeaderCell': string;
  'unmonitoredBooksHeaderCell': string;
  'warningText': string;
}
export const cssExports: CssExports;
export default cssExports;
