blank_issues_enabled: false
contact_links:
  - name: Upstream support via Discord
    url: https://readarr.com/discord
    about: Chat with upstream Readarr users and devs on support and setup related topics.
