// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'additionalFile': string;
  'customFormatTooltip': string;
  'importError': string;
  'importing': string;
  'label': string;
  'path': string;
  'quality': string;
  'reprocessing': string;
  'virtualAdditionalFile': string;
  'virtualAuthor': string;
  'virtualBook': string;
  'virtualButtonCell': string;
  'virtualCell': string;
  'virtualIconButtonCell': string;
  'virtualIconCell': string;
  'virtualImportError': string;
  'virtualImporting': string;
  'virtualPath': string;
  'virtualQuality': string;
  'virtualReleaseGroup': string;
  'virtualRow': string;
  'virtualSize': string;
  'virtualStatusCell': string;
}
export const cssExports: CssExports;
export default cssExports;
