// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'candidate': string;
  'candidateMeta': string;
  'candidateTitle': string;
  'decisionSummary': string;
  'reason': string;
  'reasonDetail': string;
  'reasonLabel': string;
  'reasonList': string;
}
export const cssExports: CssExports;
export default cssExports;
