// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'acceptedSuggestion': string;
  'acceptedSuggestionActions': string;
  'acceptedSuggestionDetail': string;
  'acceptedSuggestionTitle': string;
  'bulkSelect': string;
  'errorMessage': string;
  'filterContainer': string;
  'filterText': string;
  'footer': string;
  'importMode': string;
  'leftButtons': string;
  'rightButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
