// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'additionalFile': string;
  'customFormatTooltip': string;
  'importError': string;
  'importing': string;
  'label': string;
  'path': string;
  'quality': string;
  'reprocessing': string;
}
export const cssExports: CssExports;
export default cssExports;
