// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'linkAuthorControls': string;
  'linkedAuthorRow': string;
  'linkedAuthorsList': string;
  'summary': string;
}
export const cssExports: CssExports;
export default cssExports;
