// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'linkAuthorControls': string;
  'linkedAuthorRow': string;
  'linkedAuthorsList': string;
  'suggestionConfidence': string;
  'suggestionList': string;
  'suggestionMain': string;
  'suggestionReason': string;
  'suggestionReasons': string;
  'suggestionRow': string;
  'suggestions': string;
  'suggestionsTitle': string;
  'summary': string;
}
export const cssExports: CssExports;
export default cssExports;
