// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'column': string;
  'path': string;
  'row': string;
  'selectedContainer': string;
  'warning': string;
  'warningText': string;
}
export const cssExports: CssExports;
export default cssExports;
