// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'copyBlock': string;
  'descriptionList': string;
  'list': string;
}
export const cssExports: CssExports;
export default cssExports;
