// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bookNavigationButton': string;
  'bookNavigationButtons': string;
  'bookUpButton': string;
  'contentContainer': string;
  'filterIcon': string;
  'innerContentBody': string;
  'metadataComparison': string;
  'metadataComparisonActions': string;
  'metadataComparisonBadge': string;
  'metadataComparisonExplanation': string;
  'metadataComparisonField': string;
  'metadataComparisonGrid': string;
  'metadataComparisonHeader': string;
  'metadataComparisonLabel': string;
  'metadataComparisonNotice': string;
  'metadataComparisonRow': string;
  'metadataComparisonStatus': string;
  'metadataComparisonSummary': string;
  'metadataComparisonTitle': string;
  'metadataComparisonValues': string;
  'metadataConfidenceScoring': string;
  'metadataConfidenceSource': string;
  'metadataConfidenceSourceGrid': string;
  'metadataConfidenceSourceMeta': string;
  'metadataConfidenceSummary': string;
  'metadataDrillInField': string;
  'metadataDrillInHint': string;
  'metadataDrillInSection': string;
  'metadataDrillInSectionTitle': string;
  'metadataDrillInSummary': string;
  'metadataDrillInTitle': string;
  'metadataDrillInValues': string;
  'metadataStatusCount': string;
  'metadataStatusCounts': string;
  'metadataStatusCountsCompact': string;
  'selectedTab': string;
  'tab': string;
  'tabContent': string;
  'tabList': string;
}
export const cssExports: CssExports;
export default cssExports;
