// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bookNavigationButton': string;
  'bookNavigationButtons': string;
  'bookUpButton': string;
  'contentContainer': string;
  'filterIcon': string;
  'innerContentBody': string;
  'metadataComparison': string;
  'metadataComparisonBadge': string;
  'metadataComparisonExplanation': string;
  'metadataComparisonField': string;
  'metadataComparisonGrid': string;
  'metadataComparisonHeader': string;
  'metadataComparisonLabel': string;
  'metadataComparisonNotice': string;
  'metadataComparisonRow': string;
  'metadataComparisonStatus': string;
  'metadataComparisonSummary': string;
  'metadataComparisonTitle': string;
  'metadataComparisonValues': string;
  'selectedTab': string;
  'tab': string;
  'tabContent': string;
  'tabList': string;
}
export const cssExports: CssExports;
export default cssExports;
